package uk.ac.bangor.meander.detectors.preprocessors;

import Jama.Matrix;
import org.junit.Assert;
import org.junit.Test;
import uk.ac.bangor.meander.detectors.stats.support.PrincipalComponents;

/**
 * @author Will Faithfull
 */
public class PCATest {

    // 10x5 uniform random noise as generated by MATLAB's `rand()` function.
    final double[][] DATA = new double[][]{
            {0.814723686393179, 0.157613081677548, 0.655740699156587, 0.706046088019609, 0.438744359656398},
            {0.905791937075619, 0.970592781760616, 0.035711678574190, 0.031832846377421, 0.381558457093008},
            {0.126986816293506, 0.957166948242946, 0.849129305868777, 0.276922984960890, 0.765516788149002},
            {0.913375856139019, 0.485375648722841, 0.933993247757551, 0.046171390631154, 0.795199901137063},
            {0.632359246225410, 0.800280468888800, 0.678735154857773, 0.097131781235848, 0.186872604554379},
            {0.097540404999410, 0.141886338627215, 0.757740130578333, 0.823457828327293, 0.489764395788231},
            {0.278498218867048, 0.421761282626275, 0.743132468124916, 0.694828622975817, 0.445586200710899},
            {0.546881519204984, 0.915735525189067, 0.392227019534168, 0.317099480060861, 0.646313010111265},
            {0.957506835434298, 0.792207329559554, 0.655477890177557, 0.950222048838355, 0.709364830858073},
            {0.964888535199277, 0.959492426392903, 0.171186687811562, 0.034446080502909, 0.754686681982361}};

    // As computed by MATLAB's `pca()` function.
    final double[][] EXPECTED_COEFF = new double[][]{
            {-0.440047394431897, 0.807439060712517, 0.313467855263844, 0.090523789819685, -0.218960729543799},
            {-0.534022230231456, -0.354553713988755, -0.318789572286274, 0.505494706902657, -0.481622498862266},
            {0.425402387675710, -0.197084926924895, 0.675257739529347, 0.249255756374515, -0.511946181994454},
            {0.581370945864737, 0.427506326351045, -0.529136369712345, 0.408184854032703, -0.180682017423195},
            {-0.047108174836915, -0.027012953213402, 0.253284029838399, 0.712416477646711, 0.652197119610704}
    };

    @Test
    public void testPCA() {
        PrincipalComponents principalComponents = new PrincipalComponents(new Matrix(DATA));

        Matrix coeff = principalComponents.getCoeff();

        // Our coefficients should match those computed by MATLAB assuming we've done our job.
        for (int i = 0; i < coeff.getRowDimension(); i++) {
            for (int j = 0; j < coeff.getColumnDimension(); j++) {
                // .abs because sign is not significant in PCA coefficients
                Assert.assertEquals(Math.abs(EXPECTED_COEFF[i][j]), Math.abs(coeff.get(i, j)), 0.000001);
            }
        }
    }
}